### ISSUE TITLE
Geofield Map not appearing in Application

### ISSUE THREAD

**Issue by ronraney** [signalpoint/geofield#13]
I followed this tutorial, 'Building Mobile Aps by Example':
https://www.youtube.com/watch?v=Q8-G8g-ixi4

This corresponds to the Geotag photo tutorial here:
http://tylerfrankenstein.com/code/build-mobile-app-geo-tag-photo

The presentation on YouTube takes the Geotag tutorial one step further by displaying the Position field as a Geofield Map. I kept getting an error displaying the Positon field as a map. After hours of trying different things, I got a Google map to display in my Drupal installation. What worked for me was to apply a patch in this directory: sites/all/modules/geofield-7.x-2.3/geofield. This allowed me to put an API Google map key into the configuration settings of the geofield map module. 
 
My problem now is that the map won't display in my DrupalGap application. I'm guessing there might need to be some type of adjustment to the geofield module inside the application/app/modules directory. Maybe I am just missing something simple.

I am clearly missing the Google API key in the application. Here are the console errors:
util.js:210 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keysTA.j @ util.js:210
js:34 Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error

- I did add the Google maps JS file in my application index file. 
- I do have the Article display set to show geofield map for the position field

Thanks in advance.

**Comment by ronraney** [comment]
Here is where I found the patch
https://www.drupal.org/node/2757953

**Comment by ronraney** [comment]
Problem solved:

<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
    async defer></script>

The JS file needed my Google API Key. This is probably the preferred version with the changes to Google Maps API and key requirements.

In the DrupalGap docs, this is the the script tag suggested to use:

<script type="text/javascript" src="//maps.googleapis.com/maps/api/js"></script>

**Comment by ronraney** [comment]
`<script type="text/javascript" src="//maps.googleapis.com/maps/api/js"></script>`
This is the tag suggested to use in the DrupalGap docs.

```
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
    async defer></script>
```

You can include your key in the script tag. This solved my problem!

**Comment by signalpoint** [comment]
Thanks, I'm glad it is working. I've added this note to the docs: https://github.com/signalpoint/DrupalGap/commit/9014028234885848565bd268aaf887326f7add33
