### ISSUE TITLE
Location is not getting stored to the node

### ISSUE THREAD

**Issue by gpanag** [signalpoint/geofield#2]
Hello,
this is a great and very useful module. My issue is that the location, although is displaying correclty in the device after I press the button, it is not getting stored to the node.

I tested this on two android devices (4.2.2 and 4.4) with the same results. The site is build with drupal 7.31, geofield 7.x-2.1 and no additional modules on the fields side. For DrupalGap I use the development snapshot 7.x-1.x-alpha, as stated in the post (But I also tried the latest).

After some testing it seems that the only way to store the location is to edit (and specifically change) the textfields of latitude and longitude. Strange thing is that even if I edit them and then return them to the original values (the ones from the "get location") they dont get stored (the _geofield_field_widget_form_change function doesnt fire, tried with the alert).

**Comment by gpanag** [comment]
Ok I solved my issue although cant say if this is the right way to go.
I added a change event to the text input after the get the coordinates (just on one of the textfields was enough):

navigator.geolocation.getCurrentPosition(
        function(position) {

```
    $('#' + lat_id).val(position.coords.latitude);
    $('#' + lon_id).val(position.coords.longitude);

     $('#' + lat_id).change();
```

Now the _geofield_field_widget_form_change function fires after I press the "get location" button and values store correctly to the node.
Also forgot to mention that I also changed the key of the assemble function from:

field_key.use_key = false;

to :

field_key.value = 'geom';

which was also needed.
What do you make out of this?

**Comment by signalpoint** [comment]
@gpanag Thank you for your assistance debugging and resolving this issue. I'm added your changes to the module (with a slight modification).

Here is the original comment transcript between us: http://www.tylerfrankenstein.com/comment/1349#comment-1349

**Comment by gpanag** [comment]
Thank you Tyler for your guidance and this great module.
